def throwException(self):
    raise Exception('GIIIIIIII')

myList =[[1,2,3],[5,5,6]]
try:
    for item in myList:
        for item2 in item:
            if item2 == 1:
                try:
                    throwException()
                except Exception, e:
                    print str(e)
            print item2
except Exception, e:
    print str(e)